---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Run stat
      stat:
        path: "{{ verify_path }}"
      register: _is_test_user

    - name: Be sure it exists
      assert:
        that: _is_test_user.stat.isdir
